# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e692158479845bde2c4de30866a5a6bbb13c296bebdd02d953c085b4047b992b2eed155291372dd34aa2dc091056b5e27374ac6468b83a9eb0908fee40f972d3

test:
  secret_key_base: cf0b50673f5faf19946ffeab629f9fd15683169c5240ff28a7fb7266ea85ed5cef358a27dce673eba16b50241c1f61d43d15119ea666830ee8d7e4d57280adc7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
